// Generated by BUCKLESCRIPT VERSION 4.0.1, PLEASE EDIT WITH CARE
'use strict';

var BezierEasing$LayoutAnimationRe = require("./BezierEasing.bs.js");

var timestep = 16.667 * 1.0;

function linear(x) {
  return x;
}

var easeIn = BezierEasing$LayoutAnimationRe.bezier(0.42, 0.0, 1.0, 1.0);

var easeOut = BezierEasing$LayoutAnimationRe.bezier(0.0, 0.0, 0.58, 1.0);

var easeInEaseOut = BezierEasing$LayoutAnimationRe.bezier(0.42, 0.0, 0.58, 1.0);

var StaticEasingFunctions = /* module */[
  /* linear */linear,
  /* easeIn */easeIn,
  /* easeOut */easeOut,
  /* easeInEaseOut */easeInEaseOut
];

function generateStaticKeyframes(ease, duration, delay) {
  var numSteps = duration / timestep;
  var timestep$1 = 1.0 / numSteps;
  var numSteps_ = numSteps | 0;
  var keyframes = new Array(numSteps_);
  var currentX = 0.0;
  for(var _i = 1; _i <= numSteps_; ++_i){
    keyframes.push(ease(currentX));
    currentX += timestep$1;
  }
  keyframes.push(1.0);
  return {
          keyframes: keyframes,
          duration: duration,
          delay: delay
        };
}

function generateKeyframes($staropt$star, $staropt$star$1, duration) {
  var ease = $staropt$star !== undefined ? $staropt$star : /* EaseInEaseOut */3;
  var delay = $staropt$star$1 !== undefined ? $staropt$star$1 : 0.0;
  var f;
  switch (ease) {
    case 0 : 
        f = linear;
        break;
    case 1 : 
        f = easeIn;
        break;
    case 2 : 
        f = easeOut;
        break;
    case 3 : 
        f = easeInEaseOut;
        break;
    
  }
  return generateStaticKeyframes(f, duration, delay);
}

var timestepCoefficient = 1.0;

var springFactor = 0.5;

var linear$1 = /* Linear */0;

var easeIn$1 = /* EaseIn */1;

var easeOut$1 = /* EaseOut */2;

var easeInEaseOut$1 = /* EaseInEaseOut */3;

exports.timestepCoefficient = timestepCoefficient;
exports.springFactor = springFactor;
exports.timestep = timestep;
exports.StaticEasingFunctions = StaticEasingFunctions;
exports.linear = linear$1;
exports.easeIn = easeIn$1;
exports.easeOut = easeOut$1;
exports.easeInEaseOut = easeInEaseOut$1;
exports.generateStaticKeyframes = generateStaticKeyframes;
exports.generateKeyframes = generateKeyframes;
/* easeIn Not a pure module */
